If(db_id(N'$(DATABASE_NAME)') IS NULL) BEGIN CREATE DATABASE $(DATABASE_NAME) END; 
GO
 
use $(DATABASE_NAME);
GO  

ALTER DATABASE $(DATABASE_NAME) SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE $(DATABASE_NAME) SET ALLOW_SNAPSHOT_ISOLATION ON;


